theme: jekyll-theme-cayman
title: Simultaneous Optimization of Assignments and Goal Formations for Multiple Robots with Variable Rotation, Scale and Translation
github:
  is_project_page: false
description: false
